---
title: "Publications"
---

A list of my publications


***

#### 2022

<span class = "text-success">Taylor, R.</span>, Tomić, I., Aagten-Murphy, D., & Bays, P. M. (2022). Working memory is updated by reallocation of resources from obsolete to new items. *Attention, Perception, & Psychophysics*, 1-15 ([pdf](https://link.springer.com/article/10.3758/s13414-022-02584-2))

#### 2020

Schneegans, S., <span class = "text-success">Taylor, R.</span>, & Bays, P. M. (2020). Stochastic sampling provides a unifying account of visual working memory limits. *Proceedings of the National Academy of Sciences, 117(34)*, 20959-20968 ([pdf](https://www.pnas.org/doi/epdf/10.1073/pnas.2004306117))

<span class = "text-success">Taylor, R.</span>, & Bays, P. M. (2020). Theory of neural coding predicts an upper bound on estimates of memory variability. *Psychological Review, 127(5)*, 700 ([pdf](https://psycnet.apa.org/fulltext/2020-19842-001.pdf))

#### 2018

<span class = "text-success">Taylor, R.</span>, & Bays, P. M. (2018). Efficient coding in visual working memory accounts for stimulus-specific variations in recall. *Journal of Neuroscience, 38(32)*, 7132-7142 ([pdf](https://www.jneurosci.org/content/jneuro/38/32/7132.full.pdf))

Bays, P. M., & <span class = "text-success">Taylor, R.</span> (2018). A neural model of retrospective attention in visual working memory. *Cognitive Psychology, 100*, 43-52 ([pdf](https://reader.elsevier.com/reader/sd/pii/S0010028517302645?token=2D25E60E7FA2ECFBE59E34B2372E0935898A6081D8FC2722E3E3A46C748A91DF118921F2113E17AC3B42881C4EFE39DF&originRegion=us-east-1&originCreation=20230507084750))

#### 2017

<span class = "text-success">Taylor, R.</span>, Thomson, H., Sutton, D., & Donkin, C. (2017). Does working memory have a single capacity limit?. *Journal of Memory and Language, 93*, 67-81 ([pdf](http://www2.psy.unsw.edu.au/users/cdonkin/publications/jml17.pdf))

Konstantinidis, E., <span class = "text-success">Taylor, R. T. </span>, & Newell, B. R. (2018). Magnitude and incentives: revisiting the overweighting of extreme events in risky decisions from experience. *Psychonomic Bulletin & Review, 25(5)*, 1925-1933 ([pdf](https://link.springer.com/article/10.3758/s13423-017-1383-8))

Hayes, B. K., Dunn, J. C., Joubert, A., & <span class = "text-success">Taylor, R.</span> (2017). Comparing single‐and dual‐process models of memory development. *Developmental Science, 20(6)*, e12469 ([pdf](https://onlinelibrary.wiley.com/doi/am-pdf/10.1111/desc.12469))

#### 2016

Kary, A., <span class = "text-success">Taylor, R.</span>, & Donkin, C. (2016). Using Bayes factors to test the predictions of models: A case study in visual working memory. *Journal of Mathematical Psychology, 72*, 210-219 ([pdf](http://www2.psy.unsw.edu.au/users/cdonkin/publications/jmp16.pdf))

Donkin, C., Kary, A., Tahir, F., & <span class = "text-success">Taylor, R.</span> (2016). Resources masquerading as slots: Flexible allocation of visual working memory. *Cognitive Psychology, 85*, 30-42 ([pdf](https://d1wqtxts1xzle7.cloudfront.net/47290784/cp16b-libre.pdf?1468742742=&response-content-disposition=inline%3B+filename%3DResources_masquerading_as_slots_Flexible.pdf&Expires=1683453391&Signature=Y46~9NuEgvRcXssJKWAX8F9nTHXu8Ch4XLcTx41Q5T2vgF-geMaLmLLRQgj~zb3RQsyVdO2CGhuoakLbfQ7u-ju~2PdQoUbJxTOF6Eiy~rHXFuA3DOgQjROCWdMFcZah18e0~cqJ3qvXK65VzY1A0MyzBnLa~QhpzdciZrXdSyl20DRpsVmPYknxRTwdeHYP5oxtTjcjcch0LZlqx2uU9Hf5evtPoIa1aGvjiJmSFfx9azJV4AzScZ16uTbiPCTMOKNRbyrilhnOSnLXQyzl~wG7v4awBdEIznv8zQzFs~Ajs-WefaPWPaxQHvrubaWE5q-~G83I3usz9KSlsk-quQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA))




